package com.sprintqa.class48;
 
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.jupiter.api.DisplayName;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class WebDriverExampleTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		// Setup and load Webdriver for Chrome
		System.setProperty("webdriver.chrome.driver","C:\\Users\\lanar\\Documents\\Selenium\\SeleniumExample\\webdrivers\\chromedriver.exe");
		driver = new ChromeDriver();
		// Setup and load Webdriver for Firefox
//		System.setProperty("webdriver.chrome.driver", "/Users/mpmeloche/Development/eclipse/workspace/SeleniumExamples/webdrivers/geckodriver");		
//		driver = new FirefoxDriver();
		// This is necessary if we want to execute any JavaScript commands
		js = (JavascriptExecutor) driver;
		
		// This is used to load test data
		vars = new HashMap<String, Object>();
	}

	
	@After
	public void tearDown() {
		driver.close();
		driver.quit();
	}

	@Test
	@DisplayName(value = "WebDriver Test")
	public void loginTest() {
		// 1 | open browser with WebDriver | / | |
		driver.get("http://skookii.com/");
		// 2 | setWindowSize | 1280x877 | |
		driver.manage().window().setSize(new Dimension(1280, 877));

		// 3 | Change page to about us through location bar
		driver.navigate().to("http://skookii.com/about-skookii/");

		// 4 | Refresh the page
		driver.navigate().refresh();
		
		// 5 | Verify what page the driver is on
		String url = driver.getCurrentUrl();
		System.out.println(url);

		// 6 | Click the browsers back button
		driver.navigate().back();

		url = driver.getCurrentUrl();
		System.out.println(url);
		
		// 7 | Click the browsers forward button		
		driver.navigate().forward();

		url = driver.getCurrentUrl();
		System.out.println(url);

		// 8| get the page title
		String title = driver.getTitle();
		System.out.println(title);
	}
}
