package com.sprintqa.class48;

import java.util.Map;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.jupiter.api.DisplayName;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class WebElementExampleTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		// Setup and load ChromeDriver
		System.setProperty("webdriver.chrome.driver", "/Users/mpmeloche/Development/eclipse/workspace/SeleniumExamples/webdrivers/chromedriver");
		driver = new ChromeDriver();
	}

	
	@After
	public void tearDown() {
		driver.close();
		driver.quit();
	}

	@Test
	@DisplayName(value = "WebDriver Test")
	public void loginTest() {
		// 1 | open browser with WebDriver | / | |
		driver.get("https://www.saucedemo.com/");
		// 2 | setWindowSize | 1280x877 | |
		driver.manage().window().setSize(new Dimension(1280, 877));
		
		// 4 | click | name=username | |
		WebElement nameElement = driver.findElement(By.id("user-name"));
		nameElement.click();
		nameElement.sendKeys("standard_user");

		// 6 | click | name=password | |
		WebElement password = driver.findElement(By.id("password"));
		password.click();
		// 7 | type | name=password | 87654321 |
		password.sendKeys("secret_sauce");
		// 8 | click | css=.btn > span:nth-child(1) | |

		// 10 | click | linkText=Log Out | |
		driver.findElement(By.tagName("form")).submit();
	}
}
